# Configurações de Build para o Netlify
[build]
  # Comando que o Netlify executará para construir o site
  command = "npm run build"
  
  # Diretório onde o Netlify publicará os arquivos do site
  publish = "dist" # <-- CORREÇÃO AQUI
  
  # Diretório base para o build (onde o Netlify deve rodar o 'npm run build')
  base = "frontend"

# Regra de redirecionamento para Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
